# N.B.: This file gets copied over test.yml in continuous integration. It is
# committed to version control unencrypted.
#
:admin:
  :localpass: password
  :materials_report_list: "example@example.org"
  :tech_mail_list: "example@example.org"
:amqp:
  :fail_if_no_peer_cert: false
  :heartbeat: 10
  :host: databank
  :password: password
  :port: 5671
  :ssl: false
  :user: databank
  :verify: verify_none
  :verify_peer: false
:aws:
  :region: us-east-2
  :s3_mode: false
:datacite:
  :endpoint: na
  :password: na
  :shoulder: na
  :url_base: na
  :username: na
:datacite_test:
  :endpoint: api.test.datacite.org
  :password: ${{ secrets.DATACITE_TEST_PASSWORD }}
  :shoulder: ${{ secrets.DATACITE_TEST_SHOULDER }}
  :url_base: "https://handle.test.datacite.org"
  :username: ${{ secrets.DATACITE_TEST_USERNAME }}
:delayed_job_pid_dir: /tmp
:db:
  :password: medusa
  :username: databank
:downloader:
  :endpoint: na
  :host: na
  :password: password
  :port: 8080
  :realm: request_creators
  :ssl: false
  :user: databank
:experts:
  :endpoint: ${{ secrets.EXPERTS_ENDPOINT }}
  :illinois_external_org_id: ${{ secrets.EXPERTS_EXTERNAL_ORG_ID }}
  :key: ${{ secrets.EXPERTS_KEY }}
  :org_id: ${{ secrets.EXPERTS_ORG_ID }}
  :publisher_id: ${{ secrets.EXPERTS_PUBLISHER_ID }}
:iiif:
  :draft_base:   /tmp
  :medusa_base:  /tmp
  :url_base: http://cantaloupe:8182/iiif/2
:ldap:
  :host: na
  :password: na
  :username: na
:key_prefix: idbci
:medusa:
  :datasets_url_base: na
  :file_group_url: na
  :incoming_queue: na
  :outgoing_queue: na
:medusa_info:
  :host: na
  :password: na
  :port: na
  :ssl: na
  :user: na
:recaptcha:
  :secret_key: na
  :site_key: na
:root_url_text: "http://localhost:3000"
:storage:
  :draft_path: /tmp
  :draft_type: filesystem
  :medusa_path: /tmp
  :medusa_type: filesystem
  :tmp_path: /tmp
:system_user:
  :email: "idb@mailinator.edu"
  :name: "Databank System"
:tasks_url: na
:tmpdir : /tmp
:website:
  :window:
    :default: 25
    :min: 1
    :max: 500
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: whateverdoesnotmatter
