# used by docker-test.sh

version: "3.7"
services:
  databank-test:
    build:
      context: .
      dockerfile: docker/databank/Dockerfile-test
    depends_on: # docker-compose will NOT actually wait for these to start, hence the `sleep` in the command
      - sunspot
      - postgres
      - rabbitmq
      - memcached
      - sqs-mock
      - minio
    ports:
      - "3000:3000"
    command: bash -c 'sleep 40 && RAILS_ENV=test bundle exec rails db:drop db:create db:schema:load && curl "http://sunspot:8983/solr/admin/cores?action=CREATE&name=test&instanceDir=test" && RAILS_ENV=test bundle exec rails minio:ensure_local_buckets && RAILS_ENV=test bundle exec rails local_identity:make_testers && RAILS_ENV=test bundle exec rails sunspot:reindex && RAILS_ENV=test bin/delayed_job start && RAILS_ENV=test bundle exec rails test'