require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/curator_reports", type: :request do
  let(:admin_user) { FactoryBot.create(:user, :admin) }
  
  before(:each) do
    log_in admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # CuratorReport. As you add validations to CuratorReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      requestor_name: "Test Name",
      requestor_email: "test@example.com",
      report_type: "Sample Type",
      storage_root: "reports",
      storage_key: "key123",
      notes: "Some notes"
    }
  end

  let(:invalid_attributes) do
    {
      requestor_name: nil,
      requestor_email: "not-an-email",
      report_type: nil,
      storage_root: nil,
      storage_key: nil,
      notes: nil
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      CuratorReport.create! valid_attributes
      get curator_reports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      curator_report = CuratorReport.create! valid_attributes
      get curator_report_url(curator_report)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_curator_report_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      curator_report = CuratorReport.create! valid_attributes
      get edit_curator_report_url(curator_report)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CuratorReport" do
        expect {
          post curator_reports_url, params: { curator_report: valid_attributes }
        }.to change(CuratorReport, :count).by(1)
      end

      it "redirects to the created curator_report" do
        post curator_reports_url, params: { curator_report: valid_attributes }
        expect(response).to redirect_to(curator_report_url(CuratorReport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CuratorReport" do
        expect {
          post curator_reports_url, params: { curator_report: invalid_attributes }
        }.to change(CuratorReport, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post curator_reports_url, params: { curator_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        {
          requestor_name: "Updated Name",
          requestor_email: "updated@example.com",
          report_type: "Updated Type",
          storage_root: "updated_root",
          storage_key: "updated_key123",
          notes: "Updated notes"
        }
      end
      it "updates the requested curator_report" do
        curator_report = CuratorReport.create! valid_attributes
        patch curator_report_url(curator_report), params: { curator_report: new_attributes }
        curator_report.reload

        expect(curator_report.requestor_name).to eq(new_attributes[:requestor_name])
        expect(curator_report.requestor_email).to eq(new_attributes[:requestor_email])
        expect(curator_report.report_type).to eq(new_attributes[:report_type])
        expect(curator_report.storage_root).to eq(new_attributes[:storage_root])
        expect(curator_report.storage_key).to eq(new_attributes[:storage_key])
        expect(curator_report.notes).to eq(new_attributes[:notes])
      end

      it "redirects to the curator_report" do
        curator_report = CuratorReport.create! valid_attributes
        patch curator_report_url(curator_report), params: { curator_report: new_attributes }
        curator_report.reload
        expect(response).to redirect_to(curator_report_url(curator_report))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        curator_report = CuratorReport.create! valid_attributes
        patch curator_report_url(curator_report), params: { curator_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested curator_report" do
      curator_report = CuratorReport.create! valid_attributes
      expect {
        delete curator_report_url(curator_report)
      }.to change(CuratorReport, :count).by(-1)
    end

    it "redirects to the curator_reports list" do
      curator_report = CuratorReport.create! valid_attributes
      delete curator_report_url(curator_report)
      expect(response).to redirect_to(curator_reports_url)
    end
  end
end
