development:
  :storage:
    - :name: draft
      :type: <%= Rails.application.credentials[:storage][:draft_type] %>
      :path: <%= Rails.application.credentials[:storage][:draft_path] %>
    - :name: medusa
      :type: <%= Rails.application.credentials[:storage][:medusa_type] %>
      :path: <%= Rails.application.credentials[:storage][:medusa_path] %>

test:
  :storage:
    - :name: draft
      :type: <%= Rails.application.credentials[:storage][:draft_type] %>
      :path: <%= Rails.application.credentials[:storage][:draft_path] %>
    - :name: medusa
      :type: <%= Rails.application.credentials[:storage][:medusa_type] %>
      :path: <%= Rails.application.credentials[:storage][:medusa_path] %>

demo:
  :storage:
    - :name: draft
      :type: s3
#      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
#      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:draft_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:draft_prefix] %>
    - :name: medusa
      :type: s3
#      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
#      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:medusa_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:medusa_prefix] %>
    - :name: globus_download
      :type: s3
#      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
#      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:globus_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:globus_download_prefix] %>
    - :name: globus_ingest
      :type: s3
#      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
#      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:draft_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:draft_prefix] %>

production:
  :storage:
    - :name: draft
      :type: s3
      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:draft_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:draft_prefix] %>
      :copy_targets: ["globus_download"]
    - :name: medusa
      :type: s3
      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:medusa_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:medusa_prefix] %>
      :copy_targets: ["globus_download"]
    - :name: globus_download
      :type: s3
      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:globus_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:globus_download_prefix] %>
    - :name: globus_ingest
      :type: s3
      :aws_access_key_id: <%= Rails.application.credentials[:aws][:access_key_id] %>
      :aws_secret_access_key: <%= Rails.application.credentials[:aws][:secret_access_key] %>
      :region: us-east-2
      :bucket: <%= Rails.application.credentials[:storage][:draft_bucket] %>
      :prefix: <%= Rails.application.credentials[:storage][:draft_prefix] %>
      :copy_targets: ["draft"]