# config/routes.rb

Rails.application.routes.draw do
  root 'welcome#index'
  get '/', to: 'welcome#index'
  post '/', to: "errors#error404"
  get '/admin', to: 'welcome#admin'
  post 'api/dataset/:dataset_key/upload', to: 'api_dataset#upload', defaults: {format: 'json'}
  post 'api/dataset/:dataset_key/datafile', to: 'api_dataset#datafile', defaults: {format: 'json'}
  draw :auth
  get '/contact', to: 'welcome#contact'
  resources :contributors
  draw :creator
  draw :curator_report
  draw :datafile
  draw :dataset
  post '/ensure_local_buckets', to: 'welcome#ensure_local_buckets'
  resources :extractor_errors
  resources :extractor_responses
  resources :extractor_tasks
  resources :funders
  draw :guide
  draw :identity
  get "/illinois_experts/example", to: "illinois_experts#example", defaults: {format: "xml"}
  get "/illinois_experts/persons", to: "illinois_experts#persons", defaults: {format: "xml"}
  resources :invitees
  draw :featured_researcher
  draw :medusa_ingest
  draw :metric
  resources :nested_items
  draw :password_reset
  get '/policies', to: 'policies#index', :as => :policies
  resources :related_materials
  get '/researcher_spotlights', to: 'featured_researchers#index'
  get '/restoration_events', to: 'restoration_events#index'
  draw :review_request
  get "/robots.:format", to: "welcome#robots"
  post "/role_switch", to: 'sessions#role_switch'
  get "/sitemap.xml", to: 'sitemaps#index', defaults: {format: 'xml'}
  post '/welcome/update_read_only_message', to: 'welcome#update_read_only_message'
  post '/clear_cache', to: 'welcome#clear_cache'
  # catch unknown routes, but ignore datatables and progress-job routes, which are generated by engines.
  match "/*a" => "errors#error404", :constraints => lambda { |req| req.path !~ /progress-job/ && req.path !~ /datatables/ }, via: [:get, :post, :patch, :delete]

end