development:
  solr:
    hostname: sunspot
    port: 8983
    log_level: WARNING
    path: /solr/development

test:
  solr:
    hostname: sunspot
    port: 8983
    log_level: WARNING
    path: /solr/test

demo:
  solr:
    hostname: aws-rabbitmq-solr-demo.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank

production:
  solr:
    hostname: solr-prod.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank