development:
  solr:
    hostname: sunspot
    port: 8983
    log_level: WARNING
    path: /solr/development

test:
  solr:
    hostname: sunspot
    port: 8983
    log_level: WARNING
    path: /solr/test

demo:
  solr:
    hostname: rabbitmq-solr-demo-rocky.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank

demo-rocky:
  solr:
    hostname: rabbitmq-solr-demo-rocky.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank

production:
  solr:
    hostname: solr-prod.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank

prod-rocky:
  solr:
    hostname: solr-prod.library.illinois.edu
    port: 8983
    log_level: WARNING
    path: /solr/databank