FROM ubuntu:22.04
FROM ruby:3.3.6

ARG rails_env=test
ENV RAILS_ENV=test
ENV RAILS_LOG_TO_STDOUT=true

RUN apt-get update && apt-get install -y \
    systemd \
    nodejs \
    libmemcached-dev \
    libmagic-dev \
    yarn \
    postgresql-client \
    memcached

RUN mkdir app
RUN mkdir data
WORKDIR app

# Copy the main application, except whatever is listed in .dockerignore.
COPY . ./

RUN cp config/databank-ci.yml config/databank-test.yml
RUN cp config/medusa-storage-ci.yml config/medusa-storage-test.yml
RUN cp config/database-ci.yml config/database.yml
RUN cp config/amqp-ci.yml config/amqp-test.yml

COPY Gemfile /tmp
COPY Gemfile.lock /tmp
RUN cd /tmp \
    && gem install bundler \
    && bundle install \
    && cd /app