class CuratorReport < ApplicationRecord
  # This model is used to generate and store pointers to of curator reports

  before_destroy :destroy_report_file
  before_destroy :remove_associated_job

  def remove_associated_job
    job = Delayed::Job.where("handler LIKE ?", "%curator_report_id: #{self.id}%").first
    job.destroy if job
  end

  def self.initiate_report_generation(report_type:, requesting_user:, notes: nil, storage_root: CuratorReport.default_storage_root)
    # temporary debug logging
    Rails.logger.warn "Initiating report generation for report type #{report_type} requested by user #{requesting_user.name} with notes: #{notes}"
    # This method is used to initiate the report generation process. It is called by the controller when a user requests a report.
    # It enqueues a background job to generate the report asynchronously.
    report = CuratorReport.create!(report_type: report_type, requestor_name: requesting_user.name, requestor_email: requesting_user.email)
    report.storage_root = storage_root
    report.storage_key = report.default_storage_key
    report.notes = notes if notes.present?
    report.save!
    # temporary debug logging
    Rails.logger.debug "Created CuratorReport with ID #{report.id}, storage root #{report.storage_root}, and storage key #{report.storage_key}"
    # create a report based on the parameters, and then enqueue a job to generate the report file and store it in S3. The report object is passed to the job so that it can update the report status and storage information when the report is generated.
    Delayed::Job.enqueue CuratorReportJob.new(report)
  end

  def self.generate_report(report)
    # This method is used to generate the report file and store it in S3. It is called by the CuratorReportJob.
    # The report is generated based on the report type, and the file is stored in S3 using the storage root and key specified in the report object.
    case report.report_type
    when Databank::ReportType::FILE_AUDIT
      CuratorReport.generate_file_audit_report(report)
    else
      # temporary debug logging for unrecognized report type
      Rails.logger.warn "report type: #{report.report_type} is not recognized. Unable to generate report."
      raise "Unknown report type: #{report.report_type}"
    end
  end

  def self.generate_file_audit_report(report)
    # This method is used to generate a file audit report. It is called by the generate_report method when the report type is FILE_AUDIT.
    # The report is generated by iterating through all datasets and their files, and recording information about each file in a CSV file.
    # The CSV file is stored in S3 using the storage root and key specified in the report object.
    require 'csv'
    csv_string = CSV.generate do |csv|
      csv << ["File Name", "Storage Root", "File Size (bytes)", "File Status", "File URL", "Dataset Title", "Dataset URL"]
      Dataset.find_each do |dataset|
        dataset.datafiles.each do |file|
          file_status = file.exists_on_storage? ? "exists" : "missing"
          csv << [file.binary_name, file.storage_root, file.binary_size, file_status, file.databank_url, dataset.title, dataset.databank_url]
        end
      end
    end
    report.current_root.copy_io_to(report.storage_key, StringIO.new(csv_string), nil, csv_string.bytesize)
  end

  def self.default_storage_root
    # This method is used to determine where the report file should be stored. It is used to store the report in S3.
    StorageManager.instance.report_root.name
  end

  def default_storage_key
    # This method is used to generate a unique storage key for the report file. It is used to store the report in S3.
    day = Time.now.strftime("%Y-%m-%d")
    time = Time.now.strftime("%H-%M-%S")
    "#{self.report_type}_report-#{self.id}_#{day}_#{time}.csv"
  end

  def download_link
    "#{IDB_CONFIG[:root_url_text]}/curator_reports/#{self.id}/download"
  end

  def download_object
    raise("invalid root type") unless current_root.root_type == :s3

    Application.aws_client.get_object(bucket: current_root.bucket, key: "#{current_root.prefix}#{self.storage_key}")
  end

  def download_path
    raise("invalid root type") unless current_root.root_type == :filesystem

    "#{Rails.root}/tmp/curator_report_#{self.id}.csv"
  end

  def current_root
    # This method is used to determine the current storage root for the report file. It is
    # used to determine where the report file is stored in S3.
    StorageManager.instance.root_set.at(self.storage_root)
  end

  def status
    # This method is used to determine the status of the report. It is used to display the status of the report in the UI.
    if current_root.exist?(self.storage_key)
      Databank::ReportStatus::AVAILABLE
    elsif self.created_at < 1.hour.ago
      Databank::ReportStatus::GENERATING
    else
      Databank::ReportStatus::PENDING
    end
  end

  def status_label_class
    # This method is used to determine the CSS class for the status label. It is used to style the status label in the UI.
    case status
    when Databank::ReportStatus::AVAILABLE
      "label-success"
    when Databank::ReportStatus::GENERATING
      "label-warning"
    when Databank::ReportStatus::PENDING
      "label-default"
    else
      "label-default"
    end
  end

  def destroy_report_file
    # This method is used to delete the report file from S3 when the report is deleted. It is called by the before_destroy callback.
    if current_root.nil? || !self.storage_key || !self.storage_root
      Rails.logger.warn "Unable to destroy report file for CuratorReport #{self.id}: current_root=#{current_root.nil?}, storage_key=#{self.storage_key.nil?}, storage_root=#{self.storage_root.nil?}"
      return nil
    end
    
    current_root.delete_content(self.storage_key) if current_root.exist?(self.storage_key)
    current_root.delete_content("#{self.storage_key}.info") if current_root.exist?("#{self.storage_key}.info")
  end

end
