class CuratorReport < ApplicationRecord
    # This model is used to generate and store pointers to of curator reports

    def self.initiate_report_generation(report_type, requesting_user, storage_root = default_storage_root)
        # This method is used to initiate the report generation process. It is called by the controller when a user requests a report.
        # It enqueues a background job to generate the report asynchronously.
        Delayed::Job.enqueue CuratorReportJob.new(report_type, requesting_user, storage_root)
    end

    def self.generate_report(report)
        # This method is used to generate the report file and store it in S3. It is called by the CuratorReportJob.
        # The report is generated based on the report type, and the file is stored in S3 using the storage root and key specified in the report object.
        case report.report_type
        when Databank::ReportType::FILE_AUDIT
            CuratorReport.generate_file_audit_report(report)
        else
            raise "Unknown report type: #{report.report_type}"
        end
    end

    def self.generate_file_audit_report(report)
        # This method is used to generate a file audit report. It is called by the generate_report method when the report type is FILE_AUDIT.
        # The report is generated by iterating through all datasets and their files, and recording information about each file in a CSV file.
        # The CSV file is stored in S3 using the storage root and key specified in the report object.
        require 'csv'
        csv_string = CSV.generate do |csv|
            csv << ["Dataset Title", "File Name", "Storage Root", "File Size (bytes)", "File Status" "Dataset URL", "File URL"]
            Dataset.find_each do |dataset|
                dataset.files.each do |file|
                    file_status = file.exists_on_storage? ? "exists" : "missing"
                    csv << [dataset.title, file.binary_name, file.storage_root, file.binary_size, file_status, dataset.databank_url, file.databank_url]
                end
            end
        end
        effective_storage_root = StorageManager.instance.find_root_by_name(report.storage_root)
        effective_storage_root.copy_io_to(report.storage_key, StringIO.new(csv_string), nil, csv_string.bytesize)
    end

    def self.default_storage_root
        # This method is used to determine where the report file should be stored. It is used to store the report in S3.
        StorageManager.instance.report_root.name
    end

    def default_storage_key
        # This method is used to generate a unique storage key for the report file. It is used to store the report in S3.
        day = Time.now.strftime("%Y-%m-%d")
        time = Time.now.strftime("%H-%M-%S")
        "#{self.id}/#{self.report_type}_report_#{day}_#{time}.csv"
    end


end
