# frozen_string_literal: true

##
# Represents an error that occurs during the extraction process
# The Illinois Data Bank Archive Extractor is a microservice that extracts metadata
# from archive-type files such as zip, tar, and tar.gz
# https://wiki.library.illinois.edu/scars/Production_Services/Illinois_Data_Bank_Archive_Extractor
#
# == Attributes
#
# * +id+ - The unique identifier for the error
# * +error_type+ - The type of error that was generated
# * +extractor_response_id+ - The id of the extractor_response that this error is associated with
# * +report+ - The report that was generated by the extractor

class ExtractorError < ApplicationRecord
end
